// eslint-disable-next-line import/no-anonymous-default-export
export default {
    container: {
        flex: 1,
        display: 'block',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '0 30px',
        minHeight: 'calc(100vh - 80px)',
        background: '#fff',
        height: '100rem',
        width: '80rem',
        margin: 'auto',
        marginTop: '5%',
        marginBottom: '5%',
    },
    sectionImageTitle: {
        background: '#fff',
        display: 'flex',
        flexDirection: 'column',
        height: '40%',
    },
    content: {
        display: 'table',
        width: '100%',
        height: '40%',
        background: '#fff',
    },
    contentImage: {
        display: 'table-cell',
        verticalAlign: 'top',
        width: '50%',
        height: '30%',
        background: '#fff',
    },
    contentText: {
        display: 'table-cell',
        verticalAlign: 'top',
        width: '100%',
        height: '30%',
        background: '#fff',
        alignItems: 'center',
    },
    image: {
        display: 'flex',
        marginLeft: '-5%',
        marginRight: '100%',
        width: '100%',
    },

    cardTitle: {
        fontSize: '2.25rem',
        color: 'rgba(241, 161, 10, 1)',
        textAlign: 'left',
        marginBottom: '3rem',
        marginTop: '2rem',
        display: 'block',
        marginLeft: '15%',
        marginRight: '0%',
        background: '#fff',


    },
    data: {
        fontSize: '1.125',
        color: 'rgba(3, 41, 55, 1)',
        textAlign: 'left',
        marginBottom: '2rem',
        marginTop: '15rem',
        display: 'block',
        marginLeft: '15%',
        background: '#fff',
    },
    subtitle: {
        fontSize: '1.5rem',
        color: 'rgba(3, 41, 55, 1)',
        textAlign: 'left',
        marginBottom: '2rem',
        marginTop: '2rem',
        display: 'block',
        marginLeft: '15%',
        background: '#fff',
    },
    mainTextContainer: {
        display: 'flex',
        background: '#fff',
        marginLeft: '20%',
        marginRight: '20%',
        marginTop: '10rem'
    },
    mainText: {
        fontSize: '1.5rem',
        display: 'block',
        marginLeft: '0%',
        marginRight: '0%',
        background: '#fff',
        width: '100%',
        height: '100%',
    },
}