// eslint-disable-next-line import/no-anonymous-default-export
export default {
    container1: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#fff',
        height: '20rem',
        width: '120rem',
        margin: 'auto',
        marginTop: '5%',
        marginBottom: '5%',
        position: 'relative'
    },
    container2: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'left',
        justifyContent: 'left',
        background: '#fff',
        height: '30rem',
        width: '82.8rem',
        margin: 'auto',
        marginTop: '5%',
        marginBottom: '5%',
        marginLeft: '31%',
        position: 'relative'
    },
    container3: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#fff',
        height: '20rem',
        width: '120rem',
        margin: 'auto',
        marginTop: '5%',
        marginBottom: '5%',
        position: 'relative'
    }, container4: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#fff',
        height: '30rem',
        width: '82.8rem',
        margin: 'auto',
        marginTop: '5%',
        marginBottom: '5%',
        marginRight: '31%',
        position: 'relative'
    }, container5: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#fff',
        height: '20rem',
        width: '120rem',
        margin: 'auto',
        marginTop: '5%',
        marginBottom: '5%',
        position: 'relative'
    }, container6: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'left',
        justifyContent: 'left',
        background: '#fff',
        height: '30rem',
        width: '82.8rem',
        margin: 'auto',
        marginTop: '5%',
        marginBottom: '5%',
        marginLeft: '31%',
        position: 'relative'
    }, container7: {
        flex: 1,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#fff',
        height: '20rem',
        width: '120rem',
        margin: 'auto',
        marginTop: '5%',
        marginBottom: '5%',
        position: 'relative'
    },
    sectionSmallCard: {
        background: '#ea9d0a',
        display: 'table',
        flexDirection: 'column',
        height: '100%',
        width: '100%'
    },
    sectionSmallCard1: {
        display: 'table-cell',
        verticalAlign: 'top',
        background: '#2d2d2d',
        flexDirection: 'column',
        height: '100%',
        width: '50%',
        padding: '0, 30px',
        marginTop: '10rem',
    },
    sectionSmallCard2: {
        display: 'table-cell',
        verticalAlign: 'top',
        background: '#ea9d0a',
        flexDirection: 'column',
        height: '100%',
        width: '70%',
        padding: '0, 30px',
        marginTop: '10rem',
    },
    contentImage: {
        display: 'table-cell',
        verticalAlign: 'top',
        width: '30%',
        height: '40%',
        background: '#fff',
    },
    image:{
        width: '100%',
        height: '100%',
        background: '#fff',
    },
    contentText: {
        display: 'table-cell',
        verticalAlign: 'top',
        alignItems: 'center',
        width: '50%',
        height: '30%',
        background: '#fff',
    },
    subtitle: {
        color: 'rgba(45, 45, 45, 1)',
        background: '#fff',
        fontSize: '1.5rem',
        fontWeight: 'bold',
        marginTop: '4rem',
        marginBottom: '1rem',
        marginLeft: '1rem',
        marginRight: '1rem',
    },
    title: {
        color: 'rgba(241, 161, 10, 1)',
        background: '#ffffff',
        fontSize: '2.25rem',
        fontWeight: 'bold',
        marginTop: '1rem',
        marginBottom: '1rem',
        marginLeft: '1rem',
        marginRight: '1rem',
    },
    description: {
        color: 'rgba(45, 45, 45, 1)',
        background: '#ffffff',
        fontSize: '1.25rem',
        marginTop: '1rem',
        marginBottom: '1rem',
        marginLeft: '1rem',
        marginRight: '1rem',
    },
}